version: "3"

services:
    mysql:
        container_name: db_m1
        image: mysql:latest
        environment:
            MYSQL_DATABASE: db_m1_2
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin123
            MYSQL_ROOT_PASSWORD: admin123
        ports:
            - 3306:3306
