version: "3"

services:
    mysql:
        container_name: mysql
        image: mysql:latest
        environment:
            MYSQL_DATABASE: db_m2
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin123
            MYSQL_ROOT_PASSWORD: admin123
        ports:
            - 3306:3306
        volumes:
            - ./test_db-master:/data   # Add this line
    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: examplepassword

volumes:
    mongo-data:
