version: '3'

services:
  mysql:
    container_name: db_m1
    image: mysql:latest
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - ./sakila-schema.sql:/docker-entrypoint-initdb.d/01-sakila-schema.sql
      - ./sakila-data.sql:/docker-entrypoint-initdb.d/02-sakila-data.sql
    ports:
      - 3306:3306
